default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 1234
  host: localhost

development:
  <<: *default
  database: trabajo20rubyonrails_development
test:
  <<: *default
  database: trabajo20rubyonrails_test
production:
  <<: *default
  database: trabajo20rubyonrails_production
  username: trabajo20rubyonrails
  password: <%= ENV["TRABAJO20RUBYONRAILS_DATABASE_PASSWORD"] %>