default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 1234
  host: localhost

development:
  <<: *default
  database: trabajo28rubyonrails_development
test:
  <<: *default
  database: trabajo28rubyonrails_test
production:
  <<: *default
  database: trabajo28rubyonrails_production
  username: trabajo28rubyonrails
  password: <%= ENV["TRABAJO28RUBYONRAILS_DATABASE_PASSWORD"] %>