default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 1234
  host: localhost

development:
  <<: *default
  database: trabajo29rubyonrails_development
test:
  <<: *default
  database: trabajo29rubyonrails_test
production:
  <<: *default
  database: trabajo29rubyonrails_production
  username: trabajo29rubyonrails
  password: <%= ENV["TRABAJO29RUBYONRAILS_DATABASE_PASSWORD"] %>